### ISSUE TITLE
Use of my personal email may be driving spam to it

### ISSUE THREAD

**Issue by ryanmcginnis** [cncf/gitdm.archive#1]
Links to this repository are the only results in a search for my personal email. If possible, I would like my email removed from the repository, and if possible I would like to replace it with my work email (which is sure to filter it). Please send me a message.

**Comment by dankohn** [comment]
We don't want to be making things easier for spambots. However, all of the emails in this repo came from the list of Kubernetes commits, of which we're trying to keep a canonical list.

We will change the @ to an ` at ` or similar and see if that helps.

**Comment by ryanmcginnis** [comment]
Sure, that works. I'll message you now the email address. Thanks!

**Comment by lukaszgryglicki** [comment]
Addresses now use `!` instead of `@`, closing.
