### ISSUE TITLE
Company name is incorrect

### ISSUE THREAD

**Issue by TakanariKo** [cncf/gitdm.archive#1018]
I noticed our company "Z Lab" was renamed and all members are belong to unknown organization "Zeppelin Lab GmbH".
Please see on the list below.

https://github.com/cncf/gitdm/blob/d7478928760b927f2859c705f77957a45bfe390b/company_developers8.txt#L6452-L6460

Our company name is not "Zeppelin Lab GmbH" but "Z Lab corporation".
https://github.com/cncf/gitdm/blob/master/src/mapping.json#L3277

ref. Our company https://github.com/zlabjp

**Comment by lukaszgryglicki** [comment]
may be some auto-mapping that was imported from LF, will check this.

**Comment by lukaszgryglicki** [comment]
Fixed.
