### ISSUE TITLE
Difficult to file PRs against this gigantic repo

### ISSUE THREAD

**Issue by jglick** [cncf/gitdm.archive#102]
When I filed #83 I used GitHub’s web UI to create a fork, edit a file, and create a PR from it. I no longer seem to be able to do that—GH complains that the text files are too big to display, and does not offer an edit button. So I cloned the repository. The clone occupies 555MiB, and this took several minutes on a fiber connection! Pushing just a few weeks’ worth of `master` changes back to my fork took a while as well, and GH warned me

```
Enumerating objects: 1177, done.
Counting objects: 100% (1177/1177), done.
Delta compression using up to 4 threads
Compressing objects: 100% (406/406), done.
Writing objects: 100% (1153/1153), 44.06 MiB | 2.74 MiB/s, done.
Total 1153 (delta 832), reused 1039 (delta 744)
remote: Resolving deltas: 100% (832/832), completed with 18 local objects.        
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
remote: warning: See http://git.io/iEPt8g for more information.        
remote: warning: File github_users.json is 84.96 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 84.80 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 84.13 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 84.11 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 84.97 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 84.12 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 81.43 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 84.88 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 84.95 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 81.62 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 81.12 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 81.53 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File github_users.json is 81.54 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
```

I think about historical blobs. Indeed even the current values are huge:

```
$ git ls-files | fgrep .json | xargs du -h | fgrep M
2.7M	src/all_unknown.json
1.1M	src/default_data.json
13M	src/genderize_cache.json
9.6M	src/geousers_cache.json
44M	src/github_users.json
19M	src/stripped.json
2.4M	src/unknown_with_any_data.json
1.1M	src/unknown_with_blog.json
1.7M	src/unknown_with_location_and_name.json
1.8M	src/unknown_with_searchable_email.json
```

If these files really need to be in source control, please put the frequently edited text files in a separate repository (or at a minimum use LFS so you only need to pay for the size of the `master` checkout), and start fresh repository history so that people can reasonably file routine PRs. I cannot imagine what I would have done had I been trying to contribute to CNCF from a location with metered or non-broadband Internet access.

**Comment by lukaszgryglicki** [comment]
OK, but all you need to do is to edit 2 files (on the GitHub UI) as described [here](https://github.com/cncf/gitdm#addingupdating-affiliation) and create a PR from the UI. This takes just a few minutes max. I will handle the rest. Actually, I do need history to track changes to those files using special tools, but I can, of course, move all those big files and their history to a separate repo and create a smaller one with just README.md and text files that are supposed to be edited and created a PRs against them. Please also take a look at the closed PRs - tens of them have been merged already.

**Comment by lukaszgryglicki** [comment]
Edit: ohhh sorry, I see what you mean, just crossed some GitHub file size for TXT files and cannot edit them in the UI. I'll try to fix this somehow.

**Comment by lukaszgryglicki** [comment]
Fixed by splitting big text files into smaller parts.

**Comment by jglick** [comment]
> Fixed by splitting big text files into smaller parts.

Good enough for now! Thanks.
