### ISSUE TITLE
ghusers.rb splitting logic for repos.txt seems very brittle

### ISSUE THREAD

**Issue by jlewi** [cncf/gitdm.archive#104]
I followed the instructions to run get_repos to produce a list which I copy pasted to repos.txt. I then ran ghusers.rb.

ghusers.rb had trouble splitting the file correctly.
https://github.com/cncf/gitdm/blob/88f4c2a8d5df61b0ba09a5ef99fac95599ef08cf/src/ghusers.rb#L77

I may be misunderstanding ruby but I think

```
  repos = str.strip.split(",\n  ")
```
Is splitting on the entire string ",\n " and not treating that string as a list of delimiters. So the code is very particular about whitespace.

The following seemed to work better for me

```
repos_raw = str.strip.split(",")
  repos = []
  repos_raw.each do |r|
    repos.push(r.strip)
  end
```

**Comment by lukaszgryglicki** [comment]
Yes, you are right, that tool just expected the output from the another tool. Thanks for reporting, I will fix that

**Comment by lukaszgryglicki** [comment]
Fixed.
