### ISSUE TITLE
Request to remove my private email address

### ISSUE THREAD

**Issue by wparad** [cncf/gitdm.archive#1076]
For some reason my private email address is exposed in this repository, and I would like it removed:
https://github.com/cncf/gitdm/blob/master/src/other_repos/gitlab_2018-07-01_2019-07-01.csv#L576

If there is some reason that having a contact email is beneficial, I'm happy to provide one.

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by wparad** [comment]
Thank you.
