### ISSUE TITLE
Same user, different case?

### ISSUE THREAD

**Issue by svrnm** [cncf/gitdm.archive#1101]
Hi,

I am not sure how to fix this, so I am raising this issue: looking at [this dashboard](https://opentelemetry.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=Cisco), I see two users being listed twice (WPH95, wph95 & Arbiv, arbiv).

They are the same users, is there a way to "merge" them? 

Thanks,

cc: @wph95 , @arbiv

**Comment by lukaszgryglicki** [comment]
Will take a look when I have some time.

**Comment by svrnm** [comment]
> Will take a look when I have some time.

Thank you!

**Comment by lukaszgryglicki** [comment]
First question would be if GitHub distinguish case or not.
Can take a look Friday the earliest.

**Comment by lukaszgryglicki** [comment]
So users aren't duplicated in GitHub_users.json and cncf-config/email-map - but they are in the dashboard, investigating this.

**Comment by lukaszgryglicki** [comment]
But on the database:
```
opentelemetry=# select * from gha_actors where id > 0 and (upper(login) = 'WPH95' or lower(login) = 'arbiv');
    id    | login |     name     | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
----------+-------+--------------+------------+-----+----------+----+-----------+--------------+-----
 12132333 | Arbiv | Yosef Arbiv  |            |     |          |    |           |              |    
 12132333 | arbiv | Yosef Arbiv  |            |     |          |    |           |              |    
  2732352 | wph95 | Penghan Wang | ni         |     |          |    |           | Nicaragua    |    
  2732352 | WPH95 | Penghan Wang | ni         |     |          |    |           | Nicaragua    |    
(4 rows)

opentelemetry=# 
```

This means users were renamed somewhere in the past.
I will update dashboard to group by `lower(login)` which should solve the issue - I'll chekc this locally first.

**Comment by lukaszgryglicki** [comment]
This [commit](https://github.com/cncf/devstats/commit/d21dcb5930261930b87cef36723489ed1d14bed7) should solve this, but I need to test locally, confirm it works, rebuild images and rebuild that dashboard's data.

**Comment by lukaszgryglicki** [comment]
Fixed and regenerated data, closing.

**Comment by svrnm** [comment]
thank you @lukaszgryglicki for looking into this and fixing it!
