### ISSUE TITLE
What is the best way to change the country affiliation?

### ISSUE THREAD

**Issue by shurup** [cncf/gitdm.archive#1107]
Hello! Some users in our organization (including me) have the Country displayed as "-" at k8s.devstats.cncf.io. I have a country set in my GitHub profile now, but probably it was not there when my user was initially added to the gitdm database. Does it mean this data isn't refreshed for all users in a while?

If so, what is the best way to fix it? I found #69 where it was made by direct modification of `src/github_users.json`, is this the only way?

**Comment by lukaszgryglicki** [comment]
Yes you should update GitHub_users.json or eventually just put a list of users and countries to be set for them here.

**Comment by shurup** [comment]
Thank you, Łukasz!
