### ISSUE TITLE
Flux: please add fluxcd/flux2

### ISSUE THREAD

**Issue by dholbach** [cncf/gitdm.archive#1200]
`fluxcd/flux2` is the official repository for Flux now. `fluxcd/flux` hasn't reached its EOL just yet, but will be archived some time soon.

**Comment by lukaszgryglicki** [comment]
Flux2 is there, see [this](https://flux.devstats.cncf.io/d/1/activity-repository-groups?orgId=1&var-period=h24&var-repogroups=All) for example, closing.
