### ISSUE TITLE
Use new CSV-formatted maintainers list

### ISSUE THREAD

**Issue by matthiasr** [cncf/gitdm.archive#1355]
Since I ran into the maintainers list spreadsheet and @amye told me it was deprecated, I did a little search and came across the reference [here](https://github.com/cncf/gitdm/blob/003cf87cf423e9f4ddb086340d70e5d782e833cc/SYNC.md#to-sync-maintainers). The [new list](http://maintainers.cncf.io/) is already a CSV, so this project might be able to use it directly?

**Comment by lukaszgryglicki** [comment]
There is no process for this currently, I can try to figure out something after my PTO, so probably in March.
Please ping me then.
I also think we already have most of those maintainers in our `github_users.json` - if not then, ideally, they can be added as all other PRs here. If that is `really` not possible, I would have to create an import that will pull maintainers and then insert to our github_users.json, also taking into account collisions - CSV only has one company, while this repo supports affiliations list per user, also different users can have a specific source of data like: `manual`, `user` or `domain` with different priorities - `user` means that affiliation data was provided by the user in a PR here, so has a top priority, probably more than any CSV.
cc @caniszczyk

**Comment by lukaszgryglicki** [comment]
I *think* we have better affiliations already here than in this CSV which only lists some final affiliations for those maintainers. If any of our current affiliations are wrong please just open a PR here as any other PR - project maintainers can ideally check if their data is OK in this repo. Closing this but feel free to reopen it anytime if there is any action item for me here.
