### ISSUE TITLE
From where affiliations are imported into DevStats

### ISSUE THREAD

**Issue by weiwei04** [cncf/gitdm.archive#152]
We want to add our company affiliations into devstatus, didn't find where to add company info like https://github.com/stackalytics/default_data

**Comment by lukaszgryglicki** [comment]
Please follow https://github.com/cncf/gitdm/blob/master/README.md#addingupdating-affiliation, create a PR against https://github.com/cncf/gitdm/blob/master/developers_affiliations1.txt or https://github.com/cncf/gitdm/blob/master/developers_affiliations2.txt or https://github.com/cncf/gitdm/blob/master/developers_affiliations3.txt file.

**Comment by weiwei04** [comment]
Thanks, I want to know how to add a new company like `Qiniu`, I didn't find a file contains authoritative company info like 
```json
        {
            "domains": ["qiniu.com"],
            "company_name": "Qiniu",
            "aliases": [
                "Qiniu Limited", "Shanghai Qiniu Information Technology Co., Ltd.", "Qiniu Storage", "上海七牛信息技术有限公司"
            ]
        },
```

in https://github.com/stackalytics/default_data/blob/master/default_data.json

**Comment by lukaszgryglicki** [comment]
You don't add a new company. You add developers and affiliate them to a company name(s). Then other tools that you don't care about will create a new company entry and list its employees with date ranges.

So all you need to do is to add developers like this:
```
Fname Surname: email1@dom1.com, email2@dom2.com, ..., emailN@domN.com
  Company1 until YYYY-MM-DD
  Company2 until YYYY-MM-DD
...
   Qiniu [until YYYY-MM-DD]
   [Other company]
... 
```

**Comment by lukaszgryglicki** [comment]
Other tools will auto-generate company info later.
BTW: Qiniu is already defined here: https://github.com/cncf/gitdm/blob/master/company_developers2.txt#L15716-L15747 - but you don't edit this file - it's auto-generated.

**Comment by weiwei04** [comment]
Thanks, I get it :)

**Comment by lukaszgryglicki** [comment]
great, I'm waiting for a PR then.
