### ISSUE TITLE
how to get xieyanker in stackalytics

### ISSUE THREAD

**Issue by timyinshi** [cncf/gitdm.archive#167]
hi,everyone,xieyanker commit a pr and the pr is merged,why cannot find xieyanker in stackalytics:
xieyanker work for inspur,in stackalytics can not find him:
https://www.stackalytics.com/cncf?company=inspur
the pr is:
https://github.com/kubernetes/kube-state-metrics/pull/777

**Comment by lukaszgryglicki** [comment]
This repo is not related to stackalytics, closing.

**Comment by timyinshi** [comment]
where can get find xieyanker'commit record?

**Comment by timyinshi** [comment]
@lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
Search for `xieyanker`:
- https://raw.githubusercontent.com/cncf/gitdm/master/src/cncf-config/email-map
- https://github.com/cncf/gitdm/blob/master/company_developers2.txt#L3005
- https://github.com/cncf/gitdm/blob/master/developers_affiliations2.txt#L32169
- https://github.com/cncf/gitdm/blob/master/developers_affiliations3.txt#L9620
- https://raw.githubusercontent.com/cncf/gitdm/master/src/all_affs.csv
