### ISSUE TITLE
Why didn't my company name change to Huawei in kubeedge.devstats.cncf.io ?

### ISSUE THREAD

**Issue by kexun** [cncf/gitdm.archive#174]
I've updated the configuration to change my company to Huawei, but the company on kubeedge.devstats.cncf.io is still NetEase.

Pull requests:  https://github.com/cncf/gitdm/pull/172
![image](https://user-images.githubusercontent.com/6123010/62520275-d49d6700-b85f-11e9-83fc-c8394805f7cf.png)

![image](https://user-images.githubusercontent.com/6123010/62520007-3a3d2380-b85f-11e9-9ca5-17c211f1ca91.png)

**Comment by lukaszgryglicki** [comment]
It will change during the next affiliations import on DevStats.

**Comment by kexun** [comment]
tks~

**Comment by lukaszgryglicki** [comment]
@kexun I see your emails and GitHub login data updated in `cncf/gitdm` - values are OK - checked.
DevStats still has an old JSON with `NetEase` - importing affiliations is a time-consuming task and happens 1-2 times/month - but it regenerates data in all CNCF projects, including past data, so you will be updated this month, but not during the next few days.

**Comment by lukaszgryglicki** [comment]
This data is now importing on the test server. Once test server import is finished correctly, I'll update prod as well. I'll let you know.

**Comment by lukaszgryglicki** [comment]
You are already affiliated to Huawei on the test server, see:
- https://kubeedge.teststats.cncf.io/d/55/company-prs-in-repository-groups-table?orgId=1&var-period_name=Last%20decade&var-repogroups=All&var-companies=Huawei
- https://kubeedge.teststats.cncf.io/d/56/company-commits-table?orgId=1&var-repogroups=All&var-companies=Huawei&from=now-5y&to=now

**Comment by lukaszgryglicki** [comment]
Prod fixed too:
- https://kubeedge.devstats.cncf.io/d/55/company-prs-in-repository-groups-table?orgId=1&var-period_name=Last%20decade&var-repogroups=All&var-companies=Huawei
- https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1&var-repogroups=All&var-companies=Huawei&from=now-5y&to=now
