### ISSUE TITLE
Unknown company name

### ISSUE THREAD

**Issue by qw1mb0** [cncf/gitdm.archive#275]
I'd like to fix my company's name so that my name would be visible in company_developers and developers_affiliations files.
How should I do it? I'd open a PR but the automated machinery in this repo scares me.
```
$ grep asidorovj . -r
./src/all.txt:(Unknown) andrey.sidorov!flant.com asidorovj                                        4 (0.0%)
./src/all.txt:(Unknown) andrey.sidorov!flant.com asidorovj                                        4 (0.0%)
./src/alldevs.txt:(Unknown) andrey.sidorov!flant.com    asidorovj   4
./src/unknowns.txt:(Unknown)    andrey.sidorov!flant.com    asidorovj   4
./src/all_affs.csv:"andrey.sidorov!flant.com","asidorovj","(Unknown)","","config"
```

**Comment by lukaszgryglicki** [comment]
You only need to edit `developers_affiliations.txt` file, just add your GitHub username, emails list and affiliations there, or update existing if incorrect. I will take care of everything else.

**Comment by qw1mb0** [comment]
Huh, thanks! Will provide a PR shortly.
