### ISSUE TITLE
Something weird happened with a recent commit

### ISSUE THREAD

**Issue by craigbox** [cncf/gitdm.archive#366]
https://github.com/cncf/gitdm/commit/f5f939a278192d8cffafcf93c9851784dc4e33b1 added dgn at Red Hat.

https://github.com/cncf/gitdm/commit/6cf8f2fd569a01185684e19141a6600b2ce4d99b added jacob-delgado at Aspen Mesh.

https://github.com/cncf/gitdm/commit/a05aaaca4637ddcdc3ae10f2442e340ffebb3be5 munged the two somehow:

```
dgn: dgn!users.noreply.github.com
	Aspen Mesh
	Red Hat from 2100-01-01
	jacob-delgado: from 2100-01-01
```

**Comment by lukaszgryglicki** [comment]
Please create a PR fixing this, I'll merge on Monday and will try to see what happened.

**Comment by lukaszgryglicki** [comment]
Fixed by https://github.com/cncf/gitdm/pull/367
