### ISSUE TITLE
Change process for easier update PRs

### ISSUE THREAD

**Issue by mattfarina** [cncf/gitdm.archive#4]
I found my data was incorrect (dates/companies). The process of updating this appears to require running scripts (e.g., `./rerun_data.sh`) that can take some time to run.

Could the process instead have it so that these files are not stored in Git and are generated at the time the data is used (or deploy time)? This could save from errors introduced by end users.

**Comment by dankohn** [comment]
We'll clarify it. The idea is that you should only need to update one file
in your pull request. We'll then run the scripts when we accept the PR to
modify the resulting files, and/or when we pull the info into DevStats.
Thanks.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by mattfarina** [comment]
So, the only file I need to update is `developers_affiliations.txt`? If I do a PR with that change nothing else is needed?

**Comment by dankohn** [comment]
Exactly.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by mattfarina** [comment]
Submitted via #5. Thanks.

**Comment by mattfarina** [comment]
Would it make it easier to manage if there was one repo with the `developers_affiliations.txt` file and documentation on how to contribute. Then everything else happens via automation via a CI system.

**Comment by lukaszgryglicki** [comment]
Good idea imho.

**Comment by lukaszgryglicki** [comment]
@dankohn I think we should create a small repo like `cncf/dev_affiliations` that would contain README with instructions to update single file `developer_affiliations.txt` and create a PR.

Repo should also contain files `company_affiliations.txt`, `email-map` (but not for update) and set of tools that will just read changed `developer_affiliations.txt` and generate the remaining two.

All other tools in `cncf/gitdm` are for creating reports so can be left in `cncf/gitdm`.
We may want to create some server to automatically update data on PR merge (for example via Travis CI success webhook - of course, I would have to add tests that check if affiliations can be updated).

**Comment by dankohn** [comment]
I strongly disagree, because I don't like underscores in repo names. So, I've created:

https://github.com/cncf/dev-affiliations

**Comment by lukaszgryglicki** [comment]
OK, thanks.

**Comment by mattfarina** [comment]
I've noticed a lot of company affiliations don't seem to be appearing on devstats. My guess is that the data is either missing or out of date for them.

If there were simple directions we could put out in mass and maybe even a simple way to check for gaps it would be useful.

**Comment by lukaszgryglicki** [comment]
I think we are quite in sync between cncf/gitdm and cncf/devstats.
cncf/devstats is using affiliations from cncf/gitdm.
If You know some affiliations that we don't have yet, can You please open PR here?
I'll merge, regenerate data and update cncf/devstats accordingly.

**Comment by mattfarina** [comment]
@lukaszgryglicki I figured devstats and gitdm were in sync. It's that most of the people I've spoken with don't even know about gitdm as a place to update affiliations.  It's also hard to find good documentation on what someone should do to update affiliations. I can understand why data might be out of date or why all.txt has a long list.

I'm curious if there is a way to make a simpler UX and help people know how to easily update. So we can get more accurate data.

**Comment by lukaszgryglicki** [comment]
Well, we're open to suggestions, currently README.md explains that you should just open PR here, updating single text file.

The first section says which file should be updated.
Some people already did that.
We're thinking about some kind of automatic cron job that will update all other files automatically, but until now this needs to be reviewed (usually by me) and if I see all is OK, I'm merging and then just run few shell scripts.

**Comment by heckj** [comment]
I just saw this referenced from the Kubernetes contribex slack channel, looked myself up, and saw the same issue - my detail was terribly out of date. What's the combined result of how to update here, still just open a PR or is there any alternate repo that I should be using? - the commentary above wasn't entirely clear to me.

**Comment by dankohn** [comment]
Sorry, we haven't made the switchover yet. Please edit as described at https://github.com/cncf/gitdm#cncf-gitdm and open a pull request.
