### ISSUE TITLE
Could I add my account into developers_affiliations*.txt by myself?

### ISSUE THREAD

**Issue by kobaji** [cncf/gitdm.archive#454]
Hi there, could you please help me resolve the following problem?

# What I want to do

The number of my issues, commits, contributions, etc. will be reflected into [this Tekton ranking](https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=commits).

# What I have found
- The website of the Tekton ranking which is shown above says that "We are determining user's company affiliation from [this file](https://github.com/cncf/devstats/blob/master/github_users.json), which is imported from cncf/gitdm." in `Description`.
- [Adding/Updating affiliation](https://github.com/cncf/gitdm/blob/master/README.md#addingupdating-affiliation) says that once we edited developers_affiliations*.txt, [github_users.json](https://github.com/cncf/devstats/blob/master/github_users.json) could be reflected.

# What I am wondering
- Could I add my account information and company I am belonging to into developers_affiliations*.txt by myself?
- Could my fellows' account be added by me? Or Do they need to add by themselves?

**Comment by lukaszgryglicki** [comment]
You can add your and your fellows' affiliations by creating PR against this repo as described [here](https://github.com/cncf/gitdm#addingupdating-affiliation).

**Comment by kobaji** [comment]
@lukaszgryglicki Thanks, your advice is absolutely helpful!!
Anyway I'll try to create new PR to contribute to Tekton.
