### ISSUE TITLE
Public CNCF Maintainer List

### ISSUE THREAD

**Issue by scottrigby** [cncf/gitdm.archive#467]
Hello 👋 

Two things:

1. I added a comment about updating my company (also while I was there, commented about another Helm member who I know just moved to another company as well). Thanks in advance for updating this, and whatever generated files come from this.
2. The [spreadsheet](https://docs.google.com/spreadsheets/d/1Pr8cyp8RLrNGx9WBAgQvBzUUmqyOv69R7QAFKhacJEM/edit#gid=262035321) seems a bit out of date? After leaving the comments above, I began the in instructions at https://github.com/cncf/gitdm/blob/master/SYNC.md#to-sync-maintainers and only got as far as step 3, and saw from a git diff that there are quite a few other differences apart from what my proposed change would be. Running the script also has failures, so I just stopped. Should I proceed in a different way?

**Comment by lukaszgryglicki** [comment]
1. That spreadsheet is updated regularly by the CNCF staff - nothing in this repo.
2. You don't need to do anything, I'm doing this periodically and will do again when new 6 CNCF projects maintainers are added there.

EDIT: actually list was recently updated, I'll check it during the next affiliations import regarding those 6 new projects. We have another process researching those affiliations in the meantime so I will do this probably about September 22nd-25th.

**Comment by scottrigby** [comment]
@lukaszgryglicki got it. Thanks 🙂
