### ISSUE TITLE
sync corp and user information from stackalytics

### ISSUE THREAD

**Issue by lovejoy** [cncf/gitdm.archive#53]
would you please sync information  from https://github.com/openstack/stackalytics/blob/master/etc/default_data.json as many people use it

**Comment by lukaszgryglicki** [comment]
Will work on this.

**Comment by lukaszgryglicki** [comment]
wip

**Comment by lukaszgryglicki** [comment]
Postponed, I have two other urgent task. Will back to this later.

**Comment by lukaszgryglicki** [comment]
This is done. Closing.
