### ISSUE TITLE
Issue with developers_affiliations

### ISSUE THREAD

**Issue by Ritikaa96** [cncf/gitdm.archive#538]
Hi,

I have created this PR: https://github.com/cncf/gitdm/pull/528
But in devstats site my company name is not showing against my name:
[keda.devstats.cncf.io](https://keda.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20month&var-metric=merged_prs&var-repogroup_name=All&var-country_name=All&var-companies=All
)
Please direct how to solve this issue.

**Comment by Ritikaa96** [comment]
Hi, @lukaszgryglicki can you please suggest any solution for this?

**Comment by lukaszgryglicki** [comment]
Affiliations are imported about weekly, I'll check DevStats JSON for correctness, but you probably just need to wait.

**Comment by Ritikaa96** [comment]
Hi @lukaszgryglicki can you please suggest any solution or the reason why it is not showing?

**Comment by Ritikaa96** [comment]
Thank you for your quick response. I checked the DevStats JSON, I found my affiliations there. I'll just have to wait then. thank you again.
