### ISSUE TITLE
Process to add missing repos?

### ISSUE THREAD

**Issue by codenrhoden** [cncf/gitdm.archive#54]
Hello,

Is there a process/approval to go through to add more repos here? There is a good portion of Kubernetes development work that is happening within the github.com/kubernetes-csi org, but none of the repos there are tracked as counting toward Kubernetes.

How does one know if a repo is okay to track, and how it should be categorized?

I was going to submit a PR that adds the relevant repos to `ghusers.rb`, but I am (1) not sure if that's allowed, (2) not sure how to make sure the repos get categorized towards Kubernetes (vs any other CNCF project, for example).

Thanks!

**Comment by dankohn** [comment]
@bgrant0607 @jdumars Could you please make a statement on behalf of SIG Architecture on whether github.com/kubernetes-csi is part of the Kubernetes project.

**Comment by bgrant0607** [comment]
kubernetes-csi is part of the project, yes.

Previous records of kubernetes github orgs:
https://docs.google.com/spreadsheets/d/1MQwsWGuQvJc_RepCFgQ9HleQD2m3-_2k8utGcPaVHKY/edit#gid=289132963
https://github.com/kubernetes/community/pull/2277/files

**Comment by dankohn** [comment]
Great. @lukaszgryglicki will get the records updated when he's back from vacation in another week.

**Comment by lukaszgryglicki** [comment]
Yes and I will also have to update `devstats`.

**Comment by lukaszgryglicki** [comment]
I'll start working on this today.

**Comment by lukaszgryglicki** [comment]
I'm adding this org, but should I create some special repository group for its repos? @bgrant0607 ?
There are 10 repos in `kubernetes-csi' org (16 including name changes):
![screen shot 2018-07-09 at 11 47 41](https://user-images.githubusercontent.com/2469783/42443500-f513f440-836d-11e8-97a5-ac09c727b640.png)

**Comment by dankohn** [comment]
Yes, the 10 repos should be part of the repo group `CSI`.

**Comment by lukaszgryglicki** [comment]
OK thanks.

**Comment by lukaszgryglicki** [comment]
Org added on devstats, `cncf/gitdm` and `cncf/devstats` affiliations will be updated tomorrow

**Comment by lukaszgryglicki** [comment]
Found some problem on `cncf/gitdm` - last phase of sync failed - I'll investigate tomorrow.

**Comment by lukaszgryglicki** [comment]
All affiliations related stuff updated to most recent state
- includes kubernetes-csi
- includes all new CNCF projects
- new actors generated and CNCF contributors list updated
- new JSON will be imported on all test/prod CNCF projects in devstats soon

Closing.
