### ISSUE TITLE
Contributors data in public repository

### ISSUE THREAD

**Issue by rajeshdeshpande02** [cncf/gitdm.archive#551]
Hi Team,

Contributors' GitHub id's or email ids are fetched to this public repo which is not good practice and also not allowed by company policies. 
so is there any way we can avoid public data exposure but still show company or individual contributions on dashboards?

**Comment by lukaszgryglicki** [comment]
If you don't want any data to be shown, just follow [this](https://github.com/cncf/gitdm/blob/master/FORBIDDEN_DATA.md).

**Comment by rajeshdeshpande02** [comment]
@lukaszgryglicki Thanks for the quick response. We have removed data using mentioned steps. But after removing from here, will contribution count still be displayed on dashboards?

**Comment by lukaszgryglicki** [comment]
In some tabular views/dashboards (under DevStats) you will only see GitHub id/handle (which is public anyway), there will be no username, no emails, and no company affiliations - since this data was removed.

**Comment by Mohit-Nain** [comment]
@lukaszgryglicki can you please suggest a way where we can contribution counts reflected under our organization name, and improve on organization ranking but not make any of the contributors official email ID public to the world?
having official email ID displayed on public platforms is a very big compliance issue for our organization side.

**Comment by Mohit-Nain** [comment]
@lukaszgryglicki  Wishing you a very Happy New Year! 
Can you please share some insights on the request made earlier about the contributions count being reflected on public dasboard

**Comment by lukaszgryglicki** [comment]
You cannot have both - just request removing email data, or only add emails with no reply artificial GitHub email ...
