### ISSUE TITLE
Unknown affiliation for email that exists in developers_affiliations*.txt

### ISSUE THREAD

**Issue by shurup** [cncf/gitdm.archive#564]
Current `src/all.txt` file lists one of our engineers in the `Developers with unknown affiliation` section:

```
(Unknown) timofey.kirillov!flant.com Timofey Kirillov                              14 (0.0%)
```

However the relevant entry (to affiliate him with the company) exists in the `developers_affiliations2.txt`:

```
distorhead: distorhead!gmail.com, distorhead!users.noreply.github.com, timofey.kirillov!flant.com
        Flant
```

There is a corresponding entry in the generated `company_developers2.txt` file as well.

Can you please shed some light on what's missing in my understanding and should anything be done to fix this? There's probably no issue at all but I don't know how I can be sure.

**Comment by lukaszgryglicki** [comment]
So please only use `company_developers*.txt` and `developers_affiliations*.txt` files, other files were not regenerated for a long time, and the main data file is `github_users.json` which is the actual file used by DevStats affiliations data.

**Comment by shurup** [comment]
Thank you very much! I just saw that `all.txt` was also recently updated (13 days ago), so I assumed: while it's automatically generated, it is still updated (from time to time) in the repo as well. I also tried to regenerate `all.txt` locally but it had some errors and I decided not to dive into these waters too deep…

So that was my wrong assumption, thanks for your kind clarification!

**Comment by lukaszgryglicki** [comment]
It indeed was updated, because we normalized company names. But it was only "fixed" (like "company name" -> "Company Name Corporation Inc." etc., affiliations data wasn't changed.
