### ISSUE TITLE
Grammatical mistakes and typos found in the README.md file

### ISSUE THREAD

**Issue by vishal-codes** [cncf/gitdm.archive#635]
I have found some grammatical mistakes and typos in the Readme.md file of this project.
For e.g:- on line no. 87 there is a typo that looks something like this "neds" instead it should be "needs".

I want to work on this file, update it and resolve the issue

**Comment by lukaszgryglicki** [comment]
Sure, please go ahead.

**Comment by vishal-codes** [comment]
@lukaszgryglicki should I commit my changes directly to master branch or create a new branch and start a pull request.

**Comment by lukaszgryglicki** [comment]
Create a PR. I don't think you *can* commit anything directly to `master`.

**Comment by being-vishal** [comment]
PR merged.
