### ISSUE TITLE
Merge ids

### ISSUE THREAD

**Issue by rshriram** [cncf/gitdm.archive#67]
Hi. I have 3 different entries. shriramr@vmware.com is my current commit ID. shriram@us.ibm.com was the previous one. rshriram@noreply.github.com is also mine (caused by creating PRs via github)

**Comment by lukaszgryglicki** [comment]
I'll do,  but please tell me what is your final affiliations list? A list of affiliations like this:
- OtherCompany < YYYY-MM-DD
- IBM < YYYY-MM-DD
- VMware (current).

**Comment by rshriram** [comment]
IBM < 2018-02-16
VMware (current)

**Comment by lukaszgryglicki** [comment]
Updated in 0a0db978d6f8890ef34fdbaf4997f77cd32fb88e, e1c575f2adc45ff4c2fc19ec8728ab74a2d5e41b and 87a0cdbaecc3781c0d60c78900b6ec9bf5f1f3d4. Closing.
