### ISSUE TITLE
Quite a few "Google LLC LLC" affiliations in dev affiliation files

### ISSUE THREAD

**Issue by SergeyKanzhelev** [cncf/gitdm.archive#763]
Found looking in devstats:

![image](https://user-images.githubusercontent.com/9950081/132297069-fcecee14-bebd-4afa-992d-8155e477282e.png)

Not sure why there are a few "Google LLC LLC" affiliations, maybe some copy/paste issue?

**Comment by lukaszgryglicki** [comment]
Not sure either, fixed the affiliations JSON, next sync will fix this.
