### ISSUE TITLE
Question: Do you know why my fellow's commit cannot be reflected in Tekton ranking?

### ISSUE THREAD

**Issue by kobaji** [cncf/gitdm.archive#796]
Hi there, (I apologize if I am asking in inappropriate location)

I am in charge of Tekton contributions and commits in my company.

My fellow, Minoru ( mnitta ) has committed to Tekton website, however his commit does not seem to be reflected in Tekton ranking.

- His commit-1: https://github.com/tektoncd/website/commit/23e5c6f507e4db985f72cbbc470eb82599b2b2ce
- His fellow's commit-2: https://github.com/tektoncd/website/commit/92e50a54c7507e450a4bc10e77a6bbab1637097e
- The ranking (last month): https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20month&var-metric=commits

Do you have any causes of not reflecting to Tekton ranking?
His information is added to both developers_affiliations and github_users.json.

- https://github.com/cncf/gitdm/blob/4a6d0591499bb089ce54e553da9aacb25570dfd8/developers_affiliations4.txt#L5583-L5584
- https://github.com/cncf/devstats/blob/master/github_users.json (around 2084537 line)

Thank you for your cooperation.

**Comment by lukaszgryglicki** [comment]
Last month is calculated once per month - this might be the first possible cause.
We also list top contributing companies, not all, so if your company only has a few commits, it is possible it's not listed there.

When you take last quarter I can [see](https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20quarter&var-metric=commits) `Fujitsu` commit listed: 
```
tekton=# select * from gha_actors where login = 'mnitta';
   id    | login  |     name     | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
---------+--------+--------------+------------+-----+----------+----+-----------+--------------+-----
 1790992 | mnitta | Minoru Nitta |            |     |          |    |           |              |    
(1 row)

tekton=# select * from gha_actors_affiliations where actor_id = 1790992;
 actor_id |  company_name   | original_company_name |       dt_from       |        dt_to        | source 
----------+-----------------+-----------------------+---------------------+---------------------+--------
  1790992 | Fujitsu Limited | Fujitsu Limited       | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | user
(1 row)
```

**Comment by kobaji** [comment]
Thank you @lukaszgryglicki for kind help. I will close this issue within today, but if I should find something new, I will be reopening.

> Last month is calculated once per month - this might be the first possible cause.

I got it, thank you for help.

Btw, in `last year`, the number of our commit should be `10` but it shows `9`. I will re-check the number.
(I just thought the pod regarding the ranking can occur some errors haha)

**Comment by kobaji** [comment]
Thank you @lukaszgryglicki for kind help.
Recently (at least 1 week) this ranking has not been updated.

https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=contributions

Not just my company, bust also large vendors such as IBM or Red Hat, show the same figures these days.

Do you know if there are any troubles with this ranking (e.g., pod is not running)?

**Comment by lukaszgryglicki** [comment]
You are right, I've tracked this down to affiliations cron job being suspended (`suspend: true`) for this (and a few other projects). I'll run affiliations import manually now and let you know. Sorry for that.

**Comment by lukaszgryglicki** [comment]
Can you check now? Data and affiliations crons were stopped, I've reenabled them, forced to run now - they just finished.

**Comment by kobaji** [comment]
Thank you very much!!
Now it seems to work correctly!!

I will keep open this issue until label ` bug` is removed.

**Comment by lukaszgryglicki** [comment]
Thanks!
