### ISSUE TITLE
Instructions for testing changes are incorrect.

### ISSUE THREAD

**Issue by vaikas** [cncf/gitdm.archive#809]
The instructions here:
https://github.com/cncf/gitdm#testing-changes

Say to run
```
./rerun_data.sh
```
But looks like it was moved to ./src/rerun_data.sh

**Comment by vaikas** [comment]
Oh, and I also just tried to
```
cd ./src
./rerun_data.sh
```

but it results in various errors, so I wonder if there are some additional steps that are required before running the tests.

**Comment by lukaszgryglicki** [comment]
Actually, those instructions are from a very long time ago.
