### ISSUE TITLE
Stale maintainers entry for jpeach

### ISSUE THREAD

**Issue by jpeach** [cncf/gitdm.archive#831]
Hi, Not sure where the entry for me in src/maintainers.csv originated, but it's now stale. I'd be happy to be removed, or if there is some source of truth for this list, please LMK and I'll try to update that.

**Comment by lukaszgryglicki** [comment]
Hi, if you just want to mark you no longer work for a given company please follow [this](https://github.com/cncf/gitdm#addingupdating-affiliation)
Just update a given text file and set so something like:
```
your-gh-login: your-email1@domain1.xyz, your-email2@domain2.abc:
  CompanyName < YYYY-MM-DD
  Independent
```
But if you want your data to be totally removed from `gitdm/devstats`, you need to add your data to the exclusion list, see instructions [here](https://github.com/cncf/gitdm/blob/master/FORBIDDEN_DATA.md).

**Comment by jpeach** [comment]
Hi @lukaszgryglicki. Is maintainers.csv special? I'm wondering if there's some input to that I ought to fix?

**Comment by lukaszgryglicki** [comment]
Ohhh this s just a file not used for anything currently.
Files used to generate affiliation data are mentioned in links I've already posted. Just the `developers_affiliationsN.txt`, `company_developersN.txt`.

**Comment by jpeach** [comment]
> Ohhh this s just a file not used for anything currently.

That's weird then. That is the only file where I am mentioned, and devstats [here](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=v1.22.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=VMware%20Inc.&var-companies=Pivotal) counts my affiliation as vmware.
