### ISSUE TITLE
Affiliation doesn't appear to be updated

### ISSUE THREAD

**Issue by tylerauerbeck** [cncf/gitdm.archive#880]
I'm going to assume that this is a foo-bar or misunderstanding on my end, but after merging: https://github.com/cncf/gitdm/pull/844 , I expected to see my affiliation updated to my new employer. However after looking at my contributions across a handful of projects (ex:  https://metallb.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1 and https://argo.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1), I see myself listed with both no affiliation and affiliation to an old employer.

Is there something additional that needs done in order to reflect my new employer besides the update here? I thought maybe there was just something on the backend that needed synced, so I waited some time before opening this issue to rule that out. Or am I perhaps just misunderstanding how the listings themselves are calculated? Any information would be greatly appreciated!

**Comment by lukaszgryglicki** [comment]
Affiliations are updated once per 4-weeks (there are >100 projects now), if your affiliation change was merged more than 4 weeks ago, please let me know - I'll check if there is any error in affiliations import and will run it manually for those 2 projects then.

**Comment by tylerauerbeck** [comment]
@lukaszgryglicki Thanks for taking a look at this. My PR looks like it was merged on Nov 16, so just a little over a month ago.

**Comment by lukaszgryglicki** [comment]
OK, I'll check tomorrow then.

**Comment by lukaszgryglicki** [comment]
JSON entries in `github_users.json` are OK.
Rolls inside those two projects `metallb` and `argo` are also OK:
```
root@devstats-node-2:~/cncf/devstats-k8s-lf/util# k exec -itn devstats-prod devstats-postgres-0 -- psql argo
psql (13.1 (Debian 13.1-1.pgdg100+1))
Type "help" for help.

argo=# select * from gha_actors a, gha_actors_affiliations af where a.id = af.actor_id and a.login = 'tylerauerbeck';
    id    |     login     |      name      | country_id | sex | sex_prob | tz | tz_offset | country_name | age | actor_id | company_name | original_company_name |       dt_from       |        dt_to        | source 
----------+---------------+----------------+------------+-----+----------+----+-----------+--------------+-----+----------+--------------+-----------------------+---------------------+---------------------+--------
 29497147 | tylerauerbeck | Tyler Auerbeck |            |     |          |    |           |              |     | 29497147 | UPMC         | UPMC                  | 1900-01-01 00:00:00 | 2018-06-25 00:00:00 | user
 29497147 | tylerauerbeck | Tyler Auerbeck |            |     |          |    |           |              |     | 29497147 | Red Hat Inc. | Red Hat Inc.          | 2018-06-25 00:00:00 | 2021-10-21 00:00:00 | user
 29497147 | tylerauerbeck | Tyler Auerbeck |            |     |          |    |           |              |     | 29497147 | Equinix Inc. | Equinix Inc.          | 2021-10-21 00:00:00 | 2100-01-01 00:00:00 | user
(3 rows)

argo=# \q
root@devstats-node-2:~/cncf/devstats-k8s-lf/util# k exec -itn devstats-prod devstats-postgres-0 -- psql metallb
psql (13.1 (Debian 13.1-1.pgdg100+1))
Type "help" for help.

metallb=# select * from gha_actors a, gha_actors_affiliations af where a.id = af.actor_id and a.login = 'tylerauerbeck';
          id          |     login     |      name      | country_id | sex | sex_prob | tz | tz_offset | country_name | age |       actor_id       | company_name | original_company_name |       dt_from       |        dt_to        | source 
----------------------+---------------+----------------+------------+-----+----------+----+-----------+--------------+-----+----------------------+--------------+-----------------------+---------------------+---------------------+--------
 -4989308712776957371 | tylerauerbeck | Tyler Auerbeck |            |     |          |    |           |              |     | -4989308712776957371 | Equinix Inc. | Equinix Inc.          | 2021-10-21 00:00:00 | 2100-01-01 00:00:00 | user
 -4989308712776957371 | tylerauerbeck | Tyler Auerbeck |            |     |          |    |           |              |     | -4989308712776957371 | Red Hat Inc. | Red Hat Inc.          | 2018-06-25 00:00:00 | 2021-10-21 00:00:00 | user
 -4989308712776957371 | tylerauerbeck | Tyler Auerbeck |            |     |          |    |           |              |     | -4989308712776957371 | UPMC         | UPMC                  | 1900-01-01 00:00:00 | 2018-06-25 00:00:00 | user
(3 rows)

metallb=# 
```
So I will just regenerate their past data manually now.

**Comment by lukaszgryglicki** [comment]
But [here](https://argo.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1) you have 2 entries for 2 companies, and your rolls list 3 companies so the looks rather good for me.

**Comment by lukaszgryglicki** [comment]
Regenerated data, should now be OK, please reopen if you think it is not.
