### ISSUE TITLE
how to disable another wrong registered company

### ISSUE THREAD

**Issue by kerthcet** [cncf/gitdm.archive#912]
Sorry to disturb, as we have two companies registered, we'd like to remove one of them, what's the steps, thanks.

**Comment by lukaszgryglicki** [comment]
This is a manual process (we import mapping from elsewhere), you can let me know that `Company A` should always be mapped to `Company B` so I will add a mapping step for this (we already have some mapped company names in `mapping.json`)

**Comment by kerthcet** [comment]
thanks @lukaszgryglicki , we'd like to always map `DaoCloud` to `DaoCloud Network Technology Co. Ltd.`, it was wrong registered.

**Comment by lukaszgryglicki** [comment]
Added an internal mapping and applied.
