### ISSUE TITLE
How to merge duplicated companies?

### ISSUE THREAD

**Issue by arminru** [cncf/gitdm.archive#954]
I noticed that both "Dynatrace" and "Dynatrace LLC" show up as separate companies while they are not. Both of them have some affiliated developers assigned.
What would be the best approach to merge both into one and to ensure future employees are mapped to the correct entity?
Should the `company-map` be used for this or would it make sense to edit all occurrences in `developer_affiliations*.txt`?
Also, `dynatrace.com` seems to be missing from `domain-map` but I think this would not change the existing affiliations.

**Comment by lukaszgryglicki** [comment]
I will do this manually, this is not a good task for a PR.
Domain mapping is irrelevant here.
Will ping you when done.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by arminru** [comment]
Thank you, @lukaszgryglicki!
