### ISSUE TITLE
User skarlso was removed

### ISSUE THREAD

**Issue by Skarlso** [cncf/gitdm.archive#991]
This PR added me and WeaveWorks affiliation. https://github.com/cncf/gitdm/pull/772

However, I was somehow removed from the list and now am nowhere to be found. :(

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
There was a conflicting affiliation and email from PR had `@` instead of `!`,  I must did something wrong on manual post-merge update, now fixing it.

**Comment by lukaszgryglicki** [comment]
Should be fixed now.

**Comment by Skarlso** [comment]
Yaay! Thank you! :)
