### ISSUE TITLE
Can't update company information

### ISSUE THREAD

**Issue by Chen-Xintong** [cncf/gitdm.archive#992]
Hi, I've submit a [PR](https://github.com/cncf/gitdm/pull/986) for my Corporation, but I still can't find my company information in [Istio dashboard](https://istio.teststats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All), how can I fix it? :-)

Or it will take a while to update personal information?

**Comment by lukaszgryglicki** [comment]
Affiliations data is imported on a 4-week basis, the next import for Istio is scheduled for 24th.
```
root@devstats-node-2:~/cncf/devstats-k8s-lf/util# k get cj -A | grep istio
devstats-test   devstats-affiliations-istio                    0 16 24 * *                               False     0        20d             456d
devstats-test   devstats-istio                                 41 1,3,5,7,9,11,13,15,17,19,21,23 * * *   False     0        90m             456d
root@devstats-node-2:~/cncf/devstats-k8s-lf/util# 
```

**Comment by Chen-Xintong** [comment]
> 

Okay, Thx!

**Comment by Chen-Xintong** [comment]
> Affiliations data is imported on a 4-week basis, the next import for Istio is scheduled for 24th.
> 
> ```
> root@devstats-node-2:~/cncf/devstats-k8s-lf/util# k get cj -A | grep istio
> devstats-test   devstats-affiliations-istio                    0 16 24 * *                               False     0        20d             456d
> devstats-test   devstats-istio                                 41 1,3,5,7,9,11,13,15,17,19,21,23 * * *   False     0        90m             456d
> root@devstats-node-2:~/cncf/devstats-k8s-lf/util# 
> ```

Okay, Thx!
